### ISSUE TITLE
How to create a shell layer

### ISSUE THREAD

**Issue by st-clair-clarke** [srleecode/domain#102]
Trying to create a shell. Using the presentation layer does not offer me any option to create a shell.

**Comment by srleecode** [comment]
The shell option was removed. A shell component is the same as a feature component. It is just the parent component in the domain, so there would be extra logic in the module. Since all the components are now in the one library there is a shell module at the root level. Any shell logic can go in that module. 
<img width="238" alt="image" src="https://github.com/srleecode/domain/assets/13536934/11dbfadd-2854-4b5b-9cfe-939c4399f2e9">
